### ISSUE TITLE
killall -9 uwsgi

### ISSUE THREAD

**Issue by perk11** [FTCr/django-uwsgi-manager#1]
You shouldn't [use `killall -9`](https://github.com/FTCr/django-uwsgi-manager/blob/master/django-uwsgi-manager.sh#L11) to stop uwsgi, this is can easily lead to data loss, and also kills ALL instances of uwsgi instead of just the current one.

You're supposed to kill pid of master process instead.

**Comment by FTCr** [comment]
Угу. Знаю. Если под одним юзером несколько демонов, то будут проблемы  с таким убийством.
А про потерю данных не понял...

**Comment by perk11** [comment]
Ну девятка принудительно убивает, не даёт данные сохранить. Зачем так делать? Делай по докам, прибивай главный процесс только.
